version: '3.8'

## docker-compose -f docker-compose.local.yml up
## docker run --name postgresql-localhost-container -p 5432:5432 -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=admin -e POSTGRES_DB=test-smartfintools-db -d postgres

services:
  app:
    build: .
    container_name: smartfintools-backend-local
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dbsmartfintools
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    container_name: smartfintools-database-local
    environment:
      POSTGRES_DB: dbsmartfintools
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

